# Generated by Django 3.2.17 on 2023-02-14 08:28

import django.core.validators
from django.db import migrations, models
import testing_2023.web.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('egn', models.CharField(max_length=10, validators=[testing_2023.web.validators.egn_validator])),
            ],
        ),
    ]
